[package]
name = "excalibur-app"
version = "0.2.0"
edition = "2021"
description = "Excalibur: An alternative entrypoint to DeFi."
authors = ["Primitive Bits, Inc."]

[dependencies]

# main excalibur application
app = { path = "../crates/app", version = "0.1.0" }
sim = { path = "../crates/sim", version = "0.1.0" }

clap = { version = "=4.4.14", features = ["derive"] }
tracing = "=0.1.40"
anyhow = "=1.0.79"
dotenv = "=0.15.0"
