simulation = "DynamicWeights"
output_directory = "analysis/volatility_targeting/static"


[agent.block_admin.BlockAdmin]
timestep_size = 15

[agent.token_admin.TokenAdmin.arbx]
name = "Arbiter Token X"
symbol = "ARBX"
decimals = 18

[agent.token_admin.TokenAdmin.arby]
name = "Arbiter Token Y"
symbol = "ARBY"
decimals = 18

# Price process parameters
[agent.price_changer.PriceChanger]
# The seed to use (optional)
seed = 2
# The number of steps in the process
num_steps = 1000
# The number of distinct paths to use
num_paths = 1
# The initial price of the asset
initial_price.fixed = 1.0
# The start time of the process
t_0.fixed = 0.0
# The end time of the process
t_n.fixed = 1.0
## Parameters for the type of process to use.
# The drift for GBM
process.GBM.drift.fixed = 0.1
# The volatility for GBM
process.GBM.volatility.start = 0.1
process.GBM.volatility.end = 1.0
process.GBM.volatility.steps = 10

# Weight settings
[agent.weight_changer.WeightChanger]
# The weight for the `token_x` in the pool
# `weight_y = 1 - weight_x`
initial_weight_x.fixed = 0.5
# The swap fee in BPs
fee.fixed = 30
## Volatility targeting specialty settings
# The frequency which weights are updated
# update_frequency = 450 # 1 update per 30 timestep day
# update_frequency = 300 # 1 update per 20 timestep day
# update_frequency = 150 # 1 update per 10 timestep day
# update_frequency = 75 # 1 update per 5 timestep day
specialty.VolatilityTargeting.update_frequency.fixed = 150
# The target volatility
specialty.VolatilityTargeting.target_volatility.fixed = 0.15
# The maximum weight change
specialty.VolatilityTargeting.max_weight_change.fixed = 0.05
# The sensitivity to volatility
specialty.VolatilityTargeting.sensitivity.fixed = 0.05

# Liquidity provider settings
[agent.lp.LiquidityProvider]
# The amount of `token_x` to provide in ether
x_liquidity.fixed = 1
# The initial price of the pair
initial_price.fixed = 1.0