[package]
name = "portfolio-in-a-box"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "piab"
path = "src/main.rs"

[workspace]
members = ["simulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
# Local
bindings = { path = "./box-contracts/out/bindings", version = "0.1.0" }
simulation = { path = "./simulation", version = "0.1.0" }

# External
tokio = { version = "1.11.0", features = ["full"] }
tracing = "0.1.37"
anyhow = "1.0.75"


[dependencies]
simulation.workspace = true
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
clap = { version = "4.4.6", features = ["derive"] }
tracing-subscriber = "0.3.17"