[package]
name = "portfolio-in-a-box"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "piab"
path = "src/main.rs"

[workspace]
members = ["simulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
# Local
simulation = { path = "./simulation", version = "0.1.0" }

# External
tokio = { version = "1.11.0", features = ["full"] }
tracing = "0.1.37"
anyhow = "1.0.75"
thiserror = "1.0.49"


[dependencies]
simulation.workspace = true
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
clap = { version = "4.4.6", features = ["derive"] }
tracing-subscriber = "0.3.17"

[dev-dependencies]
# For book
mdbook = "0.4.35"
cargo-make = "0.37.2"
mdbook-katex = "0.5.8"

[arbiter]
bindings_workspace = "simulation" # must be a valid workspace member
submodules = false # change to true if you want the submodule bindings to be generated
