[package]
name = "excalibur"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "excalibur"
path = "src/main.rs"

[workspace]
members = ["simulation", "cfmm_math", "analysis", "crates/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
alloy-primitives = { version = "0.5.1" }

# Local
simulation = { path = "./simulation", version = "0.1.0" }
cfmm_math = { path = "./cfmm_math", version = "0.1.0" }
analysis = { path = "./analysis", version = "0.1.0" }

# External
arbiter-bindings = { version = "0.1.0" }
arbiter-core = { git = "https://github.com/primitivefinance/arbiter" }
ethers = { version = "2.0.10", features = ["ws", "openssl", "rustls"] }
ethers-core = "2.0.4"

## Config and parsing
serde = "1.0.188"
serde_json = "1.0.107"
config = "0.13.3"

## Async
tokio = { version = "1.11.0", features = ["full"] }
tokio-util = "0.7.10"
async-trait = "0.1.73"

## Error and logs
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing-futures = { version = "0.2.5", default-features = false }
anyhow = "1.0.75"
thiserror = "1.0.50"


bytesize = "1.2.0"
dotenv = "0.15.0"

# Visualization
plotters = "0.3.5"

# math
RustQuant = { version = "0.0.39", features = ["seedable"] }
statrs = "0.16.0"
# Storage
linked-hash-map = "0.5.6"
directories-next = "2.0.0"
criterion = "0.5.1"

[dependencies]
# main excalibur application
app = { path = "./crates/app", version = "0.1.0" }

criterion.workspace = true
simulation.workspace = true
cfmm_math.workspace = true
analysis.workspace = true

tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
clap = { version = "4.4.6", features = ["derive"] }
tracing-subscriber.workspace = true
dotenv.workspace = true
RustQuant.workspace = true
statrs.workspace = true


[dev-dependencies]
# For book
mdbook = "0.4.35"
cargo-make = "0.37.2"
mdbook-katex = "0.5.8"

[[bench]]
name = "ui_benchmark"
harness = false
path = "benches/ui_benchmarks.rs"
