[package]
name = "Excalibur"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "piab"
path = "src/main.rs"

[workspace]
members = ["simulation", "ui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
# Local
simulation = { path = "./simulation", version = "0.1.0" }
ui = { path = "./ui", version = "0.1.0" }

# External
arbiter-core = { git = "https://github.com/primitivefinance/arbiter.git", branch = "main", features = [
    "contracts",
] }
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
anyhow = "1.0.75"
thiserror = "1.0.49"
ethers = "2.0.10"
serde = "1.0.188"
serde_json = "1.0.107"


[dependencies]
simulation.workspace = true
ui.workspace = true
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
clap = { version = "4.4.6", features = ["derive"] }
tracing-subscriber = "0.3.17"

[dev-dependencies]
# For book
mdbook = "0.4.35"
cargo-make = "0.37.2"
mdbook-katex = "0.5.8"

[arbiter]
bindings_workspace = "simulation" # must be a valid workspace member
submodules = false                # change to true if you want the submodule bindings to be generated
