[profile.default]
libs = ["contracts/lib"]
out = "contracts/out"
remappings = [
  "/solmate=contracts/lib/solmate/src",
  "@prb/math/=contracts/lib/prb-math/src/",
]
solc_version = "0.8.19"
src = "contracts/src"
bytecode_hash = "none"
cbor_metadata = false
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fmt]
bracket_spacing = true
int_types = 'long'
line_length = 80
multiline_func_header = 'params_first'
quote_style = 'double'
tab_width = 4
wrap_comments = false
