[tasks.journal]
workspace = false
script = "mdbook build journal/"

[tasks.journal-view]
workspace = false
script = "mdbook serve journal/"

[tasks.default]
dependencies = ["build", "build-docs"]  # This will build both the Rust code and the docs
