simulation = "DynamicWeights"
output_directory = "analysis/momentum/static"


[agent.block_admin.BlockAdmin]
timestep_size = 15

[agent.token_admin.TokenAdmin.arbx]
name = "Arbiter Token X"
symbol = "ARBX"
decimals = 18

[agent.token_admin.TokenAdmin.arby]
name = "Arbiter Token Y"
symbol = "ARBY"
decimals = 18

# Price process parameters
[agent.price_changer.PriceChanger]
# The seed to use (optional)
seed = 2
# The number of steps in the process
num_steps = 1000
# The number of distinct paths to use
num_paths = 1
# The initial price of the asset
initial_price.fixed = 1.0
# The start time of the process
t_0.fixed = 0.0
# The end time of the process
t_n.fixed = 1.0
## Parameters for the type of process to use.
# The drift for GBM
process.GBM.drift.fixed = 0.1
# The volatility for GBM
process.GBM.volatility.fixed = 0.35

# Portfolio manager settings
[agent.portfolio_manager.G3mPortfolioManager]
# The weight for the `token_x` in the pool
# `weight_y = 1 - weight_x`
initial_weight_x.fixed = 0.5
# The swap fee in BPs
fee.fixed = 30
## Momentum specialty settings
# The frequency which weights are updated
specialty.Momentum.update_frequency.fixed = 150

# Liquidity provider settings
[agent.lp.LiquidityProvider]
# The amount of `token_x` to provide in ether
x_liquidity.fixed = 1
# The initial price of the pair
initial_price.fixed = 1.0