simulation = "DynamicWeights"
output_directory = "analysis/dca/static"

[agent.block_admin.BlockAdmin]
timestep_size = 15

[agent.token_admin.TokenAdmin.arbx]
name = "Arbiter Token X"
symbol = "ARBX"
decimals = 18

[agent.token_admin.TokenAdmin.arby]
name = "Arbiter Token Y"
symbol = "ARBY"
decimals = 18

[agent.price_changer.PriceChanger]
seed = 1
num_steps = 36500
num_paths = 50
initial_price.fixed = 1.0
t_0.fixed = 0.0
t_n.fixed = 1.0
process.GBM.drift.fixed = 0.1
process.GBM.volatility.fixed = 0.35

[agent.weight_changer.WeightChanger]
initial_weight_x.fixed = 0.01
fee.fixed = 30
specialty.DollarCostAveraging.end_weight = 0.99
specialty.DollarCostAveraging.end_timestamp = 547485 # One before very end

[agent.lp.LiquidityProvider]
x_liquidity.fixed = 1
initial_price.fixed = 1.0