[package]
name = "simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Used throughout the workspace
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true

# Specific to this lib
arbiter-core = { git = "https://github.com/primitivefinance/arbiter.git", branch = "main", features = ["contracts"] }
ethers = "2.0.10"
serde = "1.0.188"
serde_json = "1.0.107"
config = "0.13.1"
async-trait = "0.1.73"
