scenario = "Lst"
output_directory = "analysis/lst/static"

[agent.block_admin.BlockAdmin]
timestep_size = 10000

[agent.token_admin.TokenAdmin.arbx]
name = "Wrapped Staked Eth"
symbol = "wSTETH"
decimals = 18

[agent.token_admin.TokenAdmin.arby]
name = "Wrapper Ether"
symbol = "WETH"
decimals = 18

# Price process parameters
[agent.price_changer.PriceChanger]
# True is we want to use historical daily average price data
backtest = false
# The seed to use (optional)
seed = 2
# The number of steps in the process
num_steps = 3162
# The number of distinct paths to use
num_paths = 1
# The initial price of the asset
initial_price.fixed = 1.0
# The start time of the process
t_0.fixed = 0.0
# The end time of the process
t_n.fixed = 1.0
# # The mean for OU 
process.OU.mean.fixed = 0
# The volatility for OU 
process.OU.volatility.fixed = 0.1
# The mean reversion rate for OU
process.OU.theta.fixed = -0.05

[agent.lst_manager.LstParameterManager]
rate.fixed = 0.05
timestep_size.fixed = 10000
t0.fixed = 0.0
tn.fixed = 1.0

[agent.lst_lp.LogNormalLiquidityProvider]
# The amount of `token_x` to provide in ether
initial_x_amount.fixed = 100
# The initial price of the pair
initial_price.fixed = 1.0
# inital parameters
sigma.fixed = 0.1
tau.fixed = 1.0
strike_price.fixed = 1.0
swap_fee.fixed = 0.0005
