simulation = "DynamicWeights"
output_directory = "analysis/dca/sweep"

[agent.block_admin.BlockAdmin]
timestep_size = 15

[agent.token_admin.TokenAdmin.arbx]
name = "Arbiter Token X"
symbol = "ARBX"
decimals = 18

[agent.token_admin.TokenAdmin.arby]
name = "Arbiter Token Y"
symbol = "ARBY"
decimals = 18

# Price process parameters
[agent.price_changer.PriceChanger]
# The seed to use (optional)
seed = 1
# The number of steps in the process
num_steps = 1000
# The number of distinct paths to use
num_paths = 10
# The initial price of the asset
initial_price.fixed = 1.0
# The start time of the process
t_0.fixed = 0.0
# The end time of the process
t_n.fixed = 0.1
## Parameters for the type of process to use.
# The drift for GBM
process.GBM.drift.fixed = 0.0
# The volatility for GBM
process.GBM.volatility.start = 0.1
process.GBM.volatility.end = 1.0
process.GBM.volatility.steps = 10

# Portfolio manager settings
[agent.portfolio_manager.G3mPortfolioManager]
# The weight for the `token_x` in the pool
# `weight_y = 1 - weight_x`
initial_weight_x.fixed = 0.01
# The swap fee in BPs
fee.fixed = 30
## Dollar cost averaging specialty settings
# The final weight to reach
specialty.DollarCostAveraging.end_weight = 0.99
# The amount of time to reach the final weight (in seconds)
specialty.DollarCostAveraging.end_timestamp = 14985 # One before very end

# Liquidity provider settings
[agent.lp.LiquidityProvider]
# The amount of `token_x` to provide in ether
x_liquidity.fixed = 0.01 # SINCE WE ARE SETTINGS THE WEIGHT TO 0.01 AT THE START THIS WILL BE 1 ETH TOTAL LIQUIDITY
# The initial price of the pair
initial_price.fixed = 1.0

# Swapper settings
[agent.swapper.Swapper]
num_swaps.fixed = 12
start_timestamp = 15
end_timestamp = 15000
initial_balance = 1.0
swap_direction = false