[package]
name = "analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
tracing.workspace = true
thiserror.workspace = true
ethers.workspace = true
serde.workspace = true
serde_json.workspace = true
