name: book

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  install:
    name: Install and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install mdbook
      run: |
        cd documentation
        mkdir mdbook
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo "$GITHUB_WORKSPACE/documentation/mdbook" >> $GITHUB_PATH

    - name: Install mdbook-template
      run: |
        cd documentation
        mkdir mdbook-template
        curl -sSL https://github.com/sgoudham/mdbook-template/releases/latest/download/mdbook-template-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook-template
        echo `pwd`/mdbook-template >> $GITHUB_PATH
    
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.75.0
        override: true

    - name: Install mdbook-katex
      run: |
        cargo install mdbook-katex
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Run tests
      run: |
        cd documentation
        mdbook test
