name: book

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  install:
    name: Install and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install mdbook
      run: |
        cd journal
        mkdir mdbook
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo "$GITHUB_WORKSPACE/journal/mdbook" >> $GITHUB_PATH

    - name: Install mdbook-template
      run: |
        cd journal
        mkdir mdbook-template
        curl -sSL https://github.com/sgoudham/mdbook-template/releases/latest/download/mdbook-template-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook-template
        echo `pwd`/mdbook-template >> $GITHUB_PATH
    
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.73.0
        override: true

    - name: Install mdbook-katex
      run: |
        cargo install mdbook-katex
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Run tests
      run: |
        cd journal
        mdbook test

  lint:
    runs-on: ubuntu-latest
    name: Lints
    needs: install
    steps:
      - uses: actions/checkout@v3

      - name: Install mdbook-linkcheck
        run: |
          cd journal
          mkdir mdbook-linkcheck
          curl -sSL -o mdbook-linkcheck.zip https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/latest/download/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip
          unzip mdbook-linkcheck.zip -d ./mdbook-linkcheck
          chmod +x `pwd`/mdbook-linkcheck/mdbook-linkcheck
          echo `pwd`/mdbook-linkcheck >> $GITHUB_PATH

      - name: Run linkcheck
        run: |
          cd journal
          mdbook-linkcheck --standalone