name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: cargo fmt
        run: cargo +nightly fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: cargo clippy
        run: cargo clippy --all --all-features -- -D warnings

  udeps:
    name: udeps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: install udeps
        run: cargo install --git https://github.com/est31/cargo-udeps --locked
      - name: cargo udeps
        run: cargo +nightly udeps

  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run CodeSpell
        uses: codespell-project/actions-codespell@v2.0
        with:
          check_hidden: true
          check_filenames: true
          skip: .git,Cargo.lock,target
          ignore_words_list: crate,Crate,functio