name: Rust

on: push

jobs:
  checkout:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
            - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.73.0
          override: true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Cache arbiter binary
        id: cache-arbiter
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin
          key: cargo-bin-${{ runner.os }}-arbiter-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-bin-${{ runner.os }}-arbiter-

      - name: Install arbiter
        if: steps.cache-arbiter.outputs.cache-hit != 'true'
        run: cargo install arbiter

      - name: Add Cargo to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Generate Bindings
        run: arbiter bind

      - name: List directory structure
        run: ls -R

      - name: Move Bindings
        run: |
          mv ./src/bindings/* ./simulation/src/bindings/

      - name: test
        run: cargo test --workspace --exclude bindings
        working-directory: ${{ github.workspace }}

      - name: cargo fmt
        run: cargo +nightly fmt --all -- --check
        working-directory: ${{ github.workspace }}

      - name: cargo clippy
        run: cargo clippy --all --all-features -- -A non_snake_case -D warnings
        working-directory: ${{ github.workspace }}

      - name: install udeps
        run: cargo install --git https://github.com/est31/cargo-udeps --locked

      - name: cargo udeps
        run: cargo +nightly udeps
        working-directory: ${{ github.workspace }}

  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run CodeSpell
        uses: codespell-project/actions-codespell@v2.0
        with:
          check_hidden: true
          check_filenames: true
          skip: .git,Cargo.lock,target
          ignore_words_list: crate,Crate,functio