name: test

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.73.0
          override: true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install arbiter
        run: cargo install arbiter

      - name: Generate Bindings
        run: arbiter bind

      - name: List directory structure
        run: ls -R

      - name: Move Bindings
        run: |
          mkdir -p ./simulation/src/bindings
          mv ./src/src/bindings/* ./simulation/src/bindings/


      - name: test
        run: cargo test --workspace --exclude bindings